const AttendanceTypes = {
  SET_ATTENDANCE_DATE: 'SET_ATTENDANCE_DATE',
  SET_ATTENDANCE_APPOINTMENTS: 'SET_ATTENDANCE_APPOINTMENTS',
  SET_APPOINTMENT: 'SET_APPOINTMENT',
  SET_ATTENDANCE_TEACHER: 'SET_ATTENDANCE_TEACHER',
  SET_ATTENDANCE_LESSON: 'SET_ATTENDANCE_LESSON',
  SAVE_ATTENDANCE_START: 'SAVE_ATTENDANCE_START',
  SAVE_ATTENDANCE_SUCCESS: 'SAVE_ATTENDANCE_SUCCESS',
  SAVE_ATTENDANCE_FAILURE: 'SAVE_ATTENDANCE_FAILURE',
};

export default AttendanceTypes;
