const AttendanceTypes = {
  SET_ATTENDANCE_DATE: 'SET_ATTENDANCE_DATE',
  SET_ATTENDANCE_APPOINTMENTS: 'SET_ATTENDANCE_APPOINTMENTS',
  SET_APPOINTMENT: 'SET_APPOINTMENT',
  SET_ATTENDANCE_TEACHER: 'SET_ATTENDANCE_TEACHER',
  SET_ATTENDANCE_LESSON: 'SET_ATTENDANCE_LESSON',
};

export default AttendanceTypes;
