const ClassActionsType = {
  SET_CURRENT_CLASS: 'SET_CURRENT_CLASS',
  GET_CLASSES_START: 'GET_CLASSES_START',
  GET_CLASSES_FAILURE: 'GET_CLASSES_FAILURE',
  GET_CLASSES_SUCCESS: 'GET_CLASSES_SUCCESS',
};

export default ClassActionsType;
