const ClassActionsType = {
  SET_CURRENT_CLASS_START: 'SET_CURRENT_CLASS_START',
  SET_CURRENT_CLASS_SUCCESS: 'SET_CURRENT_CLASS_SUCCESS',
  SET_CURRENT_CLASS_FAILURE: 'SET_CURRENT_CLASS_FAILURE',
  GET_CLASSES_START: 'GET_CLASSES_START',
  FETCH_CLASS_STUDENTS_START: 'FETCH_CLASS_STUDENTS_START',
  GET_CLASSES_FAILURE: 'GET_CLASSES_FAILURE',
  GET_CLASSES_SUCCESS: 'GET_CLASSES_SUCCESS',
};

export default ClassActionsType;
